name: Deploy to Salesforce Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Authenticate with Salesforce (JWT)
        run: |
          echo "${{ secrets.SF_SANDBOX_JWT_KEY }}" > server.key
          sfdx auth jwt grant --client-id ${{ secrets.SF_SANDBOX_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_SANDBOX_USERNAME }} \
            --instance-url https://test.salesforce.com

      - name: Deploy to Production
        run: |
          sfdx force:source:deploy -m LightningComponentBundle:Testcase -u kamal@cube84.com --wait 10 --verbose

      - name: Clean up
        run: rm -f server.key
