name: Deploy to Salesforce Sandbox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest                        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          export PATH=$PATH:/usr/local/bin

      - name: Check Salesforce CLI Version
        run: sfdx --version

      - name: Debug Secrets
        run: |
          echo "Client ID: ${{ secrets.SF_SANDBOX_CLIENT_ID }}"
          echo "Username: ${{ secrets.SF_SANDBOX_USERNAME }}"
          echo "Instance URL: ${{ secrets.SF_SANDBOX_URL }}"

      - name: Authenticate to Salesforce Sandbox
        run: |
          echo "${{ secrets.SF_SANDBOX_JWT_KEY }}" > server.key
          sfdx auth:jwt:grant --client-id 3MVG9lpo4.J69lykzEydu0OzPvPnokiz2VrjRskUxOhPLu0xvdr0nj.38QrmjKCPnzV68Fz536yf_UJOWthji --jwt-key-file server.key --username kamal@cube84.com --instance-url https://cube84--d360aidev2.sandbox.my.salesforce.com

      - name: Verify Authentication
        run: sfdx force:org:list

      - name: Deploy to Salesforce Sandbox
        run: sfdx force:source:deploy -p force-app -w 10 --testlevel RunLocalTests
