name: Deploy to Salesforce Sandbox

on:
  push:
    branches:
      - main  # Deploys to Sandbox when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli

      - name: Authenticate to Salesforce Sandbox
        run: |
          echo "${{ secrets.SF_SANDBOX_JWT_KEY }}" > server.key
          sfdx auth:jwt:grant --client-id 3MVG9lpo4.J69lykzEydu0OzPvPnokiz2VrjRskUxOhPLu0xvdr0nj.38QrmjKCPnzV68Fz536yf_UJOWthji --jwt-key-file server.key --username kamal@cube84.com --instance-url https://cube84--d360aidev2.sandbox.my.salesforce.com

      - name: Deploy to Salesforce Sandbox
        run: |
          sfdx force:source:deploy -p force-app/main/default/lwc --testlevel RunLocalTests

