name: All files Push to Target Repo

on:
  push:
    branches:
      - main  # Trigger on the main branch

jobs:
  push-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Kam-2"
          git config --global user.email "Kamal@cube84.com"

      - name: Push Code to New Repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.SOURCE_REPO_TOKEN }}
        run: |
          git remote add target https://x-access-token:${TARGET_REPO_TOKEN}@github.com/Kam-2/TestClientA.git
          git fetch target
          git push target main
